---
title: "In_Class_Ex05"
author: "Liu Jiaqi"
---

# GAStech

```{r}
pacman::p_load(igraph, tidygraph, ggraph, 
               visNetwork, lubridate, clock,
               tidyverse, graphlayouts)
```

```{r}
GAStech_nodes <- read_csv("data/GAStech_email_node.csv")
GAStech_edges <- read_csv("data/GAStech_email_edge-v2.csv")
```

```{r}
glimpse(GAStech_edges)
```

```{r}
GAStech_edges <- GAStech_edges %>%
  mutate(SendDate = dmy(SentDate)) %>%
  mutate(Weekday = wday(SentDate,
                        label = TRUE,
                        abbr = FALSE))
```

```{r}
glimpse(GAStech_edges)
```

```{r}
GAStech_edges_aggregated <- GAStech_edges %>%
  filter(MainSubject == "Work related") %>%
  group_by(source, target, Weekday) %>%
    summarise(Weight = n()) %>%
  filter(source!=target) %>%
  filter(Weight > 1) %>%
  ungroup()
```

```{r}
glimpse(GAStech_edges_aggregated)
```

```{r}
GAStech_graph <- tbl_graph(nodes = GAStech_nodes,
                           edges = GAStech_edges_aggregated, 
                           directed = TRUE)
```

```{r}
GAStech_graph
```

```{r}

```

# VAST MC1

```{r}
pacman::p_load(jsonlite, tidygraph, ggraph, visNetwork, tidyverse)
```

```{r}
MC1 <- jsonlite::fromJSON("data/MC1.json")
```

```{r}
MC1_nodes <- as_tibble(MC1$nodes) %>%
  select(id, type, country)
```

```{r}
MC1_edges <- as_tibble(MC1$links) %>%
  select(source, target, type, weight, key)
```
